### ISSUE TITLE
Developer experience meta-issue

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1191]
Tracking ideas to improve developer experience:

- [x] Improve build dependency chain
- [x] Consolidate common virtio code between devices (#1128, #383)
- [ ] Fuzzing
- [x] Integration test output improvements
- [ ] Auto reviewer assigning
- [x] Profiling instructions
- [x] Duplicate dependencies (#1192)

**Comment by rbradford** [comment]
Fuzzing is tracked in #1288. And I don't think auto assignment of reviewers is actually necessary any longer and not so helpful with our larger team.
