### ISSUE TITLE
Live migration gaps

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2668]
- [x] Snapshot/restore `virtio-mem` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1595
- [x] Snapshot/restore `virtio-balloon` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1598
- [x] Snapshot/restore `vhost-user` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1599
- [x] "versioning" https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1600
- [x] Dirty write tracking by the VMM (#2458)
- [ ] VFIO device migration (#2251)
- [x] vhost-user migration support (#2813)
- [x] Versioning of state (#1600)
- [ ] Handling of differing KVM version on destination
- [x] Handling of differing cpuid on destination (#2841)
- [x] Turning on dirty-page-tracking only when needed (#2858 )
- [x] Extensive testing (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2958)
- [x] Live-migration for MSHV (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2887)
- [x] Refine the source VM behavior post live-migration (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2895)
- [ ] https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3023

**Comment by likebreath** [comment]
@rbradford @sboeuf I just finished the experiments of live migration on a single Azure VM (both 'bare-metal' and 'nested'), and submitted a PR to document the steps https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2726.

I will move to migrate across two Azure VMs (with the same platform and host kernel) tomorrow, and gradually move to different platform/kernel to test how our live migration works on different CPUID and kvm version. Let me know if you have any quick comments or questions. Thanks!

**Comment by sboeuf** [comment]
>I will move to migrate across two Azure VMs (with the same platform and host kernel) tomorrow, and gradually move to different platform/kernel to test how our live migration works on different CPUID and kvm version.

Sounds good :)

**Comment by rbradford** [comment]
Closing this as the two gaps remain are already tracked separately: #3023 and #2251
