### ISSUE TITLE
Increase virtio-mmio testing coverage

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#275]
Ideally we want to fully exercise all devices with both transports.

**Comment by rbradford** [comment]
- [ ] #1441 `test_virtio_mem`
- [ ] #1443 `test_virtio_blk` (uses MQ)
- [ ] #1445 `test_multiple_network_interfaces`
